# site settings
title: Justin Grima
subtitle:
email: justintgrima@gmail.com
description: A repository of projects to explore that demonstrate my skills and abilities in the data science world.
baseurl: # the subpath of your site, e.g. /blog
url: https://justingrima.github.io # the base hostname & protocol for your site
author: Justin Grima
street_address:
city: Cairns
state: QLD
zip_code: 4870
country: Australia
phone: +61 434 006 852

# homepage tiles
tiles-source: Justin Grima # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/JustinGrima
  GitLab:
  Google-Plus:
  Instagram: https://www.instagram.com/justintime4datascience/
  LinkedIn: https://www.linkedin.com/in/justin-grima-852297155/
  Twitter:
  Facebook: https://www.facebook.com/justin.grima.5
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
